#!/usr/bin/python3
import sys
import math

def factorize(n):
    if n == 0:
        print('{}={}*{}'.format(0,0,0))
        return
    if n == 1:
        print('{}={}*{}'.format(1,1,1))
        return

    start = int(math.sqrt(n))
    if n % 2 == 0:
        print('{}={}*{}'.format(n,n//2,2))
        return
   
    for divisor in range(start + 1, 3, -2):
        if (n % divisor) == 0:
            factor1 = n//divisor
            factor2 = divisor
            print('{:d}={:d}*{:d}hereee'.format(n,factor1,factor2))
            return

    print('{}={}*{}'.format(n,n,1))

if len(sys.argv) != 2:
    print('Usage: factors <file>')
    sys.exit(1)

filename = sys.argv[1]

try:
    with open(filename, 'r') as file:
        lines = file.readlines()
except IOError:
    sys.exit(1)

for line in lines:
    n = int(line.strip())
    factorize(n) 
