#!/usr/bin/python3

import sys
import math

def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(math.sqrt(num)) + 1):
        if num % i == 0:
            return False
    return True

def factorize(n):
    if n == 0:
        print('0 has no prime factors.')
        return
    if n == 1:
        print('1 has no prime factors.')
        return

    prime_factors = []
    while n % 2 == 0:
        prime_factors.append(2)
        n //= 2
        if len(prime_factors) == 2:
            break

    for i in range(3, int(math.sqrt(n)) + 1, 2):
        while n % i == 0:
            prime_factors.append(i)
            n //= i
            if len(prime_factors) == 2:
                break

    if n > 2:
        prime_factors.append(n)

    if len(prime_factors) == 2:
        p, q = prime_factors
        print(f'{n} = {p} * {q}')
    else:
        print(f'{n} does not have two distinct prime factors.')



if len(sys.argv) != 2:
    print('Usage: factors <file>')
    sys.exit(1)

filename = sys.argv[1]

try:
    with open(filename, 'r') as file:
        lines = file.readlines()
except IOError:
    sys.exit(1)

for line in lines:
    n = int(line.strip())
    factorisation = factorize(n)
