#!/usr/bin/python3

import sys
import math

def is_prime(n):
    if n > 1:
        for i in range(2, int(n / 2) + 1):
            if(n % i) == 0:
                return(0)
        
        return(1)
    return(0)

def factorize(n):
    if n == 0:
        print('0=0*0')
        return
    if n == 1:
        print('1=1*1')
        return
    s = n//2
    if n % 2 == 0:
        if is_prime(s):
            print('{:d}={:d}*{:d}'.format(n, n//2, 2))
            return
    for i in range(s, 3, -2):
        print('in the for loop', i)
        if n % i == 0:
            if is_prime(n // i):
                factor1 = i
                factor2 = n // factor1
                print('{:d}={:d}*{:d}'.format(n, factor2, factor1))
                return
    print('{:d}={:d}*1'.format(n, n))

if len(sys.argv) != 2:
    print('Usage: factors <file>')
    sys.exit(1)

filename = sys.argv[1]

try:
    with open(filename, 'r') as file:
        lines = file.readlines()
except IOError:
    sys.exit(1)

for line in lines:
    n = int(line.strip())
    factorisation = factorize(n)
