#!/usr/bin/python3

import math
import sys

def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(math.sqrt(num)) + 1):
        if num % i == 0:
            return False
    return True

def pollards_rho(n):
    x = 2
    y = 2
    d = 1

    while d == 1:
        x = (x * x + 1) % n
        y = (y * y + 1) % n
        y = (y * y + 1) % n
        d = math.gcd(abs(x - y), n)

    return d

def factorize_rsa_number(n):
    p = pollards_rho(n)
    q = n // p
    return p, q

def main(filename):
    with open(filename, 'r') as file:
        for line in file:
            n = int(line.strip())
            p, q = factorize_rsa_number(n)
            print(f'{n}={p}*{q}')

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python rsa <file>")
    else:
        filename = sys.argv[1]
        main(filename)

